# Generated by Django 2.2.6 on 2019-11-03 16:13

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(default='幻灯片标题', max_length=30)),
                ('banner_img', models.ImageField(default='幻灯片图片', upload_to='')),
                ('banner_url', models.CharField(default='链接', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Blogtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PhotographyShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(default='照片名', max_length=30)),
                ('photo', models.ImageField(default='展示照片', upload_to='')),
                ('photo_url', models.CharField(default='照片大图链接', max_length=100)),
                ('blog_url', models.CharField(default='照片大图链接', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='标题', max_length=100)),
                ('thumbnail', models.ImageField(blank=True, upload_to='')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('blog_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blogtype')),
            ],
            options={
                'ordering': ('-created_time',),
            },
        ),
    ]
