# Generated by Django 2.2.6 on 2019-11-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_img',
            field=models.ImageField(default='幻灯片图片', upload_to='banner'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnail'),
        ),
        migrations.AlterField(
            model_name='photographyshow',
            name='photo',
            field=models.ImageField(default='展示照片', upload_to='photographyshow'),
        ),
    ]
