# Generated by Django 2.2.6 on 2019-11-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_head',
            field=models.ImageField(default='bg_ftrr.png', upload_to='user'),
        ),
    ]
