# Generated by Django 2.2.6 on 2019-11-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191105_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_head',
            field=models.ImageField(default='media/user/bg_ftrr.png', upload_to='user'),
        ),
    ]
