# Generated by Django 2.2.6 on 2019-11-05 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191105_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_head',
        ),
    ]
