# Generated by Django 2.2.6 on 2019-11-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_profile_user_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_head',
            field=models.ImageField(default='user/bg_ftrr.png', upload_to='user'),
        ),
    ]
